spring:
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  profiles: dev
  application:
    name: springcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles: USER
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://admin:123456@eureka1:7001/eureka,http://admin:123456@eureka3:7003/eureka
  instance:
    instance-id: springcloud-provider-product
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
info:
  app.name: microcloud-provider-product
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: springcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles: USER
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://admin:123456@eureka1:7001/eureka,http://admin:123456@eureka3:7003/eureka
  instance:
    instance-id: springcloud-provider-product
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
info:
  app.name: microcloud-provider-product
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$